### ISSUE TITLE
使用etcd替代zk做存储

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere-elasticjob-lite#194]
1. 调研etcd的基础api 
2. 配合原有的RegCenter接口，参考ZookeeperRegCenter，编写etcd的EtcdRegCenter类 
3. 提供etcd配置中心的Spring命名空间配置 
4. 提供etcd的Web console配置 
5. 基于Lite和Cloud的整合测试

**Comment by mengzhenbin** [comment]
go

**Comment by jiangshujian** [comment]
gogo

**Comment by yeyincai** [comment]
go  go

**Comment by soiff** [comment]
我看目前对Spring Boot的支持比较弱，最好能够提供一套Spring Boot适配器，这样能够避免过多的XML配置，支持以后跟客户端的编码就解耦了。请考虑一下~

**Comment by terrymanu** [comment]
如果提的问题与主题无关，请开启新的issue。
针对springboot的问题，已有example，请参考

**Comment by soiff** [comment]
好，我看看

**Comment by yeyincai** [comment]
调研的怎么样了

**Comment by huangyiminghappy** [comment]
go

**Comment by xiaods** [comment]
https://github.com/coreos/zetcd
Serve the Apache Zookeeper API but back it with an etcd cluster

**Comment by terrymanu** [comment]
@xiaods 多谢。之前etcd2不能满足我们的需求，etcd3的java client又还没开发完善。这个zetcd比较满足我们的需求，打算调研看看，或者等待etcd3的java client开发完成。
我们权衡一下

**Comment by Xiaobaxi** [comment]
consul或者eureka这种是否后续也考虑支持呢，因为SpringCloud支持eureka、consul？
或者可以提供一套通用的方案，让我们来自行实现？

**Comment by ryuhi** [comment]
或者可以考虑开放接口，供大家自行实现。好的实现，官方可以合并进主干

**Comment by etteeee** [comment]
想咨询一下，当前如果自己写一个EtcdRegCenter有那些地方要注意的？
仅用job-lite/不用spring配置/不用console

**Comment by Husanmao** [comment]
etcd v3现在可以使用官方出的jetcd了，但是就基础api来讲不知道满足不满足注册中心的要求，目前看临时节点和目录监控这块还需要自行适配，不知道亮哥调研的怎么样了。

**Comment by terrymanu** [comment]
expired
