### ISSUE TITLE
关于event-trace-rdb-data-source的完善

### ISSUE THREAD

**Issue by xsphere** [apache/shardingsphere-elasticjob-lite#234]
现在event和trace的信息，只能通过插入数据库的方式获取吗？我看代码eventbus处无法注册自定义的JobEventListener，能否做如下调整，让用户决定如何处理JobExecutionEvent和JobStatusTraceEvent？
即：
1）添加一通用的JobEventConfiguration，提供JobEventListener注入：
package com.dangdang.ddframe.job.event;

import java.io.Serializable;

public class JobEventGeneralConfiguration implements JobEventConfiguration, Serializable {
	/**
	 * 
	 */
	private static final long serialVersionUID = 7316422686527315073L;
	private JobEventListener listener;

	public JobEventListener getListener() {
		return listener;
	}

	public void setListener(JobEventListener listener) {
		this.listener = listener;
	}

	@Override
	public String getIdentity() {
		return "general";
	}

	@Override
	public JobEventListener createJobEventListener() throws JobEventListenerConfigurationException {
		return listener;
	}

}
2）修改com.dangdang.ddframe.job.lite.spring.job.parser.common.AbstractJobBeanDefinitionParser的如下方法：
@Override
    protected AbstractBeanDefinition parseInternal(final Element element, final ParserContext parserContext) {
        BeanDefinitionBuilder factory = BeanDefinitionBuilder.rootBeanDefinition(SpringJobScheduler.class);
        factory.setInitMethodName("init");
        factory.setDestroyMethodName("shutdown");
        if ("".equals(element.getAttribute(CLASS_ATTRIBUTE))) {
            factory.addConstructorArgValue(null);
        } else {
            factory.addConstructorArgValue(BeanDefinitionBuilder.rootBeanDefinition(element.getAttribute(CLASS_ATTRIBUTE)).getBeanDefinition());
        }
        factory.addConstructorArgReference(element.getAttribute(REGISTRY_CENTER_REF_ATTRIBUTE));
        factory.addConstructorArgValue(createLiteJobConfiguration(element));
        // 修改以前的数据库模式，直接注入监听器
        /*
        BeanDefinition jobEventConfig = createJobEventConfig(element);
        if (null != jobEventConfig) {
            factory.addConstructorArgValue(jobEventConfig);
        }
        */
        String eventTraceDataSourceName = element.getAttribute(EVENT_TRACE_RDB_DATA_SOURCE_ATTRIBUTE);
        if (!Strings.isNullOrEmpty(eventTraceDataSourceName)) {
        	factory.addConstructorArgValue(new RuntimeBeanReference(eventTraceDataSourceName));
        }
        factory.addConstructorArgValue(createJobListeners(element));
        return factory.getBeanDefinition();
    }

这样用户就可以自定义如何处理了，比如：
<job:simple id="simpleElasticJob" class="cn.jsfund.tsp.job.MyElasticJob"
		registry-center-ref="regCenter" cron="0/10 * * * * ?"
		sharding-total-count="1" sharding-item-parameters="0=A"
		job-exception-handler="cn.jsfund.tsp.job.JsfundJobExceptionHandler" event-trace-rdb-data-source="jobEventGeneralConfiguration">
		<job:listener class="cn.jsfund.tsp.job.JsfundElasticJobListener" />
	</job:simple>
	
	<bean id="jsundJobEventListener" class="cn.jsfund.tsp.job.JsfundJobEventListener"/>
	<bean id="jobEventGeneralConfiguration" class="com.dangdang.ddframe.job.event.JobEventGeneralConfiguration">
		<property name="listener" ref="jsundJobEventListener"/>
	</bean>

**Comment by kaojunsong** [comment]
hello，我也遇到了类似的问题，不想配置数据库，只想通过EventListener搜集任务执行日志，你那边解决这个问题了吗？

**Comment by terrymanu** [comment]
The new event tracing module is finished at version 3.x, it use spi to handle event tracing storage, please try it.
FYI: #822
