### ISSUE TITLE
事件追踪在数据库访问频繁的情况下有几率出现主键重复

### ISSUE THREAD

**Issue by haocao** [apache/shardingsphere-elasticjob-lite#326]
https://www.oschina.net/question/1584523_2242760

**Comment by terrymanu** [comment]
目前采用了异步的方式去发送作业开始和作业结束的事件。因此，无法保证作业开始执行的insert事件一定先于作业结束的update事件。所以这里做了一下防御性编程，如果是update先到，则改为insert。
但是也可能产生bug，就是在验证是否insert成功时，与真正insert时并未在一个事务中，进而导致主键冲突，而无法将completeTime写入数据库。

未来的版本将这里的update改为insert，将作业开始和作业结束事件都作为insert，这样可以有效避免这类问题。

**Comment by NeatGuyCoding** [comment]
将insert和update改为replace，并且原有的insert不修改completeTime，成功失败原因字段，可以解决这个问题吧。

**Comment by mmx1960** [comment]
have u had a plan to slove this ? i solved this on my own version(use code, not sql) , if you permit ， i can try to commit a pull request .

**Comment by terrymanu** [comment]
Fixed by version 2.x

**Comment by liangkaipro** [comment]
请问下2.1.5版本这个问题已经解决了吗 @terrymanu
